version: '2'
services:
  api:
    build:
      context: ./dotnet/
      dockerfile: Booking.Api.Dockerfile
    environment:
      BOOKING_API_CONNECTIONSTRING: "${BOOKING_API_CONNECTIONSTRING}"
      BOOKING_API_PASSWORD: "${BOOKING_API_PASSWORD}"
    links:
      - db:booking-database
    image: booking-api
  app:
    build: ./app/
    image: booking-app
  db:
    build: ./db/
    environment:
      BOOKING_API_PASSWORD: "${BOOKING_API_PASSWORD}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    image: booking-database
  web:
    build: ./web/
    links:
      - api:booking-api
    image: booking-web
    ports:
      - "80:80"
    volumes_from:
      - app:ro