version: '2'
services:
  api:
    build: ./api/
    ports:
      - "4590"
    volumes:
      - ./api/:/dotnet/
  app:
    build: ./app/
    ports:
      - "4591"
    volumes:
      - ./app/:/dotnet/
  db:
    build: ./database/
    ports:
      - "5432:5432"
  web:
    build: ./web/