version: '2'
services:
  api:
    build:
      context: ./dotnet/
      dockerfile: Booking.Api.Dockerfile
    environment:
      BOOKING_PASSWORD: "${BOOKING_PASSWORD}"
      BOOKING_OAUTH_SECRET: "${BOOKING_OAUTH_SECRET}"
    links:
      - db:booking-database
    image: booking-api
  app:
    build: ./app/
    image: booking-app
  db:
    build: ./db/
    environment:
      BOOKING_PASSWORD: "${BOOKING_PASSWORD}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    image: booking-database
  seed:
    build:
      context: ./dotnet/
      dockerfile: Booking.Seeder.Dockerfile
    depends_on:
      - db
    environment:
      BOOKING_PASSWORD: "${BOOKING_PASSWORD}"
    image: booking-seed
  site:
    build:
      context: ./dotnet/
      dockerfile: Booking.Website.Dockerfile
    environment:
      BOOKING_PASSWORD: "${BOOKING_PASSWORD}"
    links:
      - db:booking-database
    image: booking-site
  web:
    build: ./web/
    links:
      - api:booking-api
      - site:booking-site
    image: booking-web
    ports:
      - "80:80"
    volumes_from:
      - app:ro