version: '2'
services:
  api:
    ports:
      - "5490:4590"
    volumes:
      - ./dotnet/:/dotnet/
  app:
    volumes:
      - ./app/static/:/data/web/static/
  db:
    ports:
      - "5432:5432"
  site:
    ports:
      - "5491:4590"
    volumes:
      - ./dotnet/:/dotnet/