version: '2'
services:
  api:
    build: ./api/
    ports:
      - "4590"
    volumes:
      - ./api/:/dotnet/
  db:
    build: ./database/
    ports:
      - "5432:5432"
  web:
    build: ./web/
    volumes:
      - ./web/static/:/data/web/static/
      - ./web/www/:/data/web/www/