version: '2'
services:
  api:
    links:
      - db:booking-database
    image: booking-api
  db:
    image: booking-database
  web:
    links:
      - api:booking-api
    image: booking-web
    ports:
      - "80:80"